Unit tests for PBFT
bitwiseio/sawtooth-pbft pull request #5
Opened 2018-08-14 18:39 UTC by bridger-herman

Scope: Commits https://github.com/bitwiseio/sawtooth-pbft/commit/071987beb892077fbde8dee3289ba89e0719bc74 through https://github.com/bitwiseio/sawtooth-pbft/commit/889f6d12b18ab673a94917c90c6b8da4b7dc266a (7 commits)

This PR depends on #2 and #3.

Changes since #3:
+ Add unit tests for:
  + `timing`
  + `state`
  + `message_log`
  + `node`
+ Add materials for running unit tests in Docker

2018-08-22 21:41 UTC, agunde406 requested changes

2018-08-22 21:41 UTC, agunde406 commented on src/timing.rs
> +    fn ticker() {
Please add comments to the test describing what is being tested

2018-08-22 21:41 UTC, agunde406 commented on Cargo.toml
> +rust-crypto = "0.2"
If this is only used for testing it can be moved to a [dev-dependencies] section of the Cargo.toml file.

2018-08-22 21:41 UTC, agunde406 commented on src/main.rs
> +extern crate crypto;
If only used in tests add #[cfg(test)] above the extern crate

2018-08-22 21:41 UTC, agunde406 commented on src/state.rs
> +    #[test]
add comments describing what is being tested to all tests

2018-08-22 21:41 UTC, agunde406 commented on src/message_log.rs
> +    #[test]
add comments describing what is being tested to all tests

2018-08-22 21:41 UTC, agunde406 commented on src/node.rs
> +    fn block_valid() {
add comments describing what is being tested to all tests

2018-08-22 21:41 UTC, agunde406 commented on tests/sawtooth-pbft-test.dockerfile
> +# Copyright 2018 Bitwise IO, Inc.
If this file started off as a copy of an intel file it should include both copyrights so it looks like:

Copyright 2018 Intel Corporation
Copyright 2018 Bitwise IO, Inc.

2018-08-23 14:15 UTC, bridger-herman commented
@agunde406 Updated to address your thoughts. Added comments to all tests describing their purpose

2018-08-23 19:19 UTC, agunde406 approved these changes

2018-08-27 16:33 UTC, jsmitchell approved these changes

2018-08-27 17:54 UTC, merged