Add check for NotStarted in Checkpoint messages
bitwiseio/sawtooth-pbft pull request #9
Opened 2018-08-31 21:07 UTC by bridger-herman

Makes sure that a node can't start a checkpoint in any other phase but `NotStarted`.

2018-09-04 13:04 UTC, agunde406 approved these changes

2018-09-10 20:49 UTC, peterschwarz approved these changes

2018-09-19 20:01 UTC, agunde406 requested changes
Does not build  due to the following:
error[E0308]: mismatched types
   --> src/node.rs:242:47
    |
242 |                     self.msg_log.push_backlog(msg);
    |                                               ^^^ expected struct `sawtooth_sdk::consensus::engine::PeerMessage`, found reference
    |
    = note: expected type `sawtooth_sdk::consensus::engine::PeerMessage`
               found type `&sawtooth_sdk::consensus::engine::PeerMessage`

2018-09-20 13:44 UTC, agunde406 approved these changes

2018-09-20 17:49 UTC, peterschwarz approved these changes

2018-09-20 18:59 UTC, merged